### ISSUE TITLE
problem with NgxAdminLteModule

### ISSUE THREAD

**Issue by sajadonline** [TwanoO67/ngx-admin-lte#35]
hi
i when import NgxAdminLteModule in 
`@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    NgxAdminLteModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})`

have a error for compile 

`ERROR in ./node_modules/ngx-admin-lte/index.ts
Module build failed: Error: /home/sajad/project/pardiscrm-ng/node_modules/ngx-admin-lte/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/sajad/project/pardiscrm-ng/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/home/sajad/project/pardiscrm-ng/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/app.module.ts 11:22-46
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Failed to compile.
ERROR in node_modules/ngx-admin-lte/src/ngx-admin-lte.module.ts(14,36): error TS2345: Argument of type 'HttpClient' is not assignable to parameter of type 'HttpClient'.
  Types have separate declarations of a private property 'handler'.
`

**Comment by TwanoO67** [comment]
Hello,

Can you look if your node-modules actually contains ngx admin lte?
And if so, what does it contains ?

**Comment by sajadonline** [comment]
hi again
my package.json is 
"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "ngx-admin-lte": "^1.0.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },

and app.module.ts is

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { NgxAdminLteModule } from 'ngx-admin-lte';


import { AppComponent } from './app.component';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule, 
    NgxAdminLteModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by TwanoO67** [comment]
Ok, so it's related to the new compilation of angular5 (coming from @angular/cli)
Now it doesn't compile the TS modules anymore.
So I have to publish the package as a JS module.
And for the moment I don't know how to do that, but I request help on issue #47

If you have any idea it would be much appreciated

**Comment by TwanoO67** [comment]
should be fixed by 2.0.0-beta.10.
Can you confirm ?
