### ISSUE TITLE
Module build error.

### ISSUE THREAD

**Issue by steve-frank** [TwanoO67/ngx-admin-lte#6]
I am facing this new issue now. 
I have imported  NgxAdminLteModule in my app.module.ts like this:
`import { NgxAdminLteModule } from 'ngx-admin-lte"`

and 

```
@NgModule({
  ...
imports: [
  ...
  NgxAdminLteModule,
```

```
ERROR in ./~/ngx-admin-lte/index.ts
Module build failed: Error
    at new FatalError (C:\mayur\work\microServiceSetUp\seventhGatewayMongo\node_modules\tslint\lib\error.js:31:23)
    at Function.findConfiguration (C:\mayur\work\microServiceSetUp\seventhGatewayMongo\node_modules\tslint\lib\configuration.js:55:15)
    at parseConfigFile (C:\mayur\work\microServiceSetUp\seventhGatewayMongo\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (C:\mayur\work\microServiceSetUp\seventhGatewayMongo\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (C:\mayur\work\microServiceSetUp\seventhGatewayMongo\node_modules\tslint-loader\index.js:139:17)
 @ ./src/main/webapp/app/layouts/main/main.component.ts 16:22-46
 @ ./src/main/webapp/app/layouts/index.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
```

Can you  pls look into this.
Regards,
Gomes

**Comment by TwanoO67** [comment]
It's seems to have a problem with your ts-lint configuration...

**Comment by TwanoO67** [comment]
Have you found out the problem 
@steve-frank ?

**Comment by wilfridmaxis** [comment]
I'm facing this issue and I can't find find the problem. I replaced my ts-lint configuration with the one in bootstraping-ngx-admin app but the problem still persists. Below the error.

_ERROR in ./node_modules/ngx-admin-lte/index.ts
Module build failed: Error
    at new FatalError (C:\Users\Haiti-IFMS\eclipse-workspace\audit\node_modules\tslint\lib\error.js:31:23)
    at Function.findConfiguration (C:\Users\Haiti-IFMS\eclipse-workspace\audit\node_modules\tslint\lib\configuration.js:55:15)
    at parseConfigFile (C:\Users\Haiti-IFMS\eclipse-workspace\audit\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (C:\Users\Haiti-IFMS\eclipse-workspace\audit\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (C:\Users\Haiti-IFMS\eclipse-workspace\audit\node_modules\tslint-loader\index.js:139:17)
 @ ./src/main/webapp/app/app.module.ts 13:22-46
 @ ./src/main/webapp/app/app.main.ts_
